### PR TITLE
Add invert function (mpz_invert)

### PR DESCRIPTION
**Pull request by basiliscos**

### CODE REVIEW

**Comment by nordlow** [comment]
Thanks!

**Comment by nordlow** [comment]
Made a couple of optimizations of `invert()`.

**Comment by nordlow** [comment]
We should add an assert that your comment

```
Parameter `exp` must be positive.
```

is fulfilled. But there is no `exp` parameter. Do you mean `base` or `mod` or both?

I tried changing the sign of `mod` but that doesn't have any effect on the tests. And changing the sign of `base` doesn't trigger the `assert(success >= 0)` but gives a different answer. When does this operation fail, then?

**Comment by basiliscos** [comment]
> Parameter `exp` must be positive.

Oopps, sorry, please remove that copy-paste line :)

> . But there is no exp parameter. Do you mean base or mod or both?

neither. They both should be non-zero, but can be negative, AFAIK.

> I tried changing the sign of mod but that doesn't have any effect on the tests. And changing the sign of base doesn't trigger the assert(success >= 0) but gives a different answer. When does this operation fail, then?

Try  `15.Z.invert(25.Z)`

**Comment by nordlow** [comment]
1. Are `base` and `mod` good namings?
2. A zero `base` returns a zero. Is this wrong?

**Comment by basiliscos** [comment]
> Are base and mod good namings?

I think so. It is (symbolicallty) equivalent `base.invert(mod) ==base.powm(-1, mod)`.

> A zero base returns a zero. Is this wrong?

Well, yes. cz, `0.powm(0, N) != 1`

**Comment by nordlow** [comment]
Great, then everything should be commited on master as you wanted.

**Comment by basiliscos** [comment]
Thank you! Please, upload the new version to http://code.dlang.org/

**Comment by nordlow** [comment]
I pushed tag v0.1.1 to github. Is that sufficient?

**Comment by nordlow** [comment]
Apparently ;)

**Pull request merged**
