### PR TITLE
Add left shift (`<<=`) operator

### PR DESCRIPTION
**Pull request by Luhrel**

### CODE REVIEW

**Comment by nordlow** [comment]
Thanks!

**Comment by nordlow** [comment]
What about adding support for

1. signed integer `rhs`-parameter to `<<` and `<<=`
2. `>>` and `>>=` operator

both calling truncating (integer) divide by two, @Luhrel.

For the sake of making semantics of bit-shift operators even more conformant with builtin integer types.

Division already mimics truncating division as, for instance,

```d
    assert(27.Z / 10.Z  == 2);
    assert(27.Z /   10   == 2);
    assert(27.Z /   10UL == 2);
```

What do you think @9il?

**Comment by 9il** [comment]
I would rather go with methods like `mulPow2` to make code more obvious.

**Comment by nordlow** [comment]
> I would rather go with methods like `mulPow2` to make code more obvious.

Ok. But that makes code less substitutable and less generic.

**Comment by 9il** [comment]
The operators are good as well.  That isn't something critical.

**Comment by Luhrel** [comment]
> What about adding support for
> 
>     1. signed integer `rhs`-parameter to `<<` and `<<=`
> 
>     2. `>>` and `>>=` operator
> 
> 
> both calling truncating (integer) divide by two, @Luhrel.

It's a good idea.

**Pull request merged**
